Repository urbannoise/urban-noise-mobile-android-app, pull requests merged in 2020-05, with the labels that each got.

#22 Improve azure pipeline
  azure-pipelines.yml
Labels: :zap: improvement

#24 Feature/firebase project issue 17
  .gitignore
  app/build.gradle.kts
  app/src/debug/google-services.json
  app/src/prod/google-services.aes
  app/src/qa/google-services.aes
  base-android/build.gradle.kts
  buildSrc/build.gradle.kts
  buildSrc/src/main/kotlin/BuildDependenciesVersions.kt
  buildSrc/src/main/kotlin/BuildPlugins.kt
  buildSrc/src/main/kotlin/BuildTypes.kt
  buildSrc/src/main/kotlin/dependencies/Dependencies.kt
  buildSrc/src/main/kotlin/plugins/sonarqube.gradle.kts
  scripts/release/signing-setup.sh
Labels: :star2: feature

#23 Add scheduled pipeline for update dependencies
  .azure/build.yml
  .azure/scheduled.yml
  buildSrc/src/main/kotlin/BuildDependenciesVersions.kt
  buildSrc/src/main/kotlin/plugins/update-dependencies.gradle.kts
  gradle/wrapper/gradle-wrapper.properties
Labels: :books: investigate

#29 Create issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/documentation_request.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: :zap: improvement

#31 Create pull_request_template.md
  .github/pull_request_template.md
Labels: :zap: improvement
